In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [37]:
df = pd.read_csv("../Resources/artistDf.csv")
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 934 entries, 0 to 1034
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   X               934 non-null    int64
 1   Artist          934 non-null    object
 2   Followers       934 non-null    int64
 3   Genres          934 non-null    object
 4   NumAlbums       934 non-null    int64
 5   YearFirstAlbum  934 non-null    int64
 6   Gender          934 non-null    object
 7   Group.Solo      934 non-null    object
dtypes: int64(4), object(4)
memory usage: 65.7+ KB

In [38]:
df

,X,Artist,Followers,Genres,NumAlbums,YearFirstAlbum,Gender,Group.Solo
0,0,Ed Sheeran,52698756,"pop,uk pop",8,2011,M,Solo
1,1,Justin Bieber,30711450,"canadian pop,dance pop,pop,post-teen pop",10,2009,M,Solo
2,2,Jonas Brothers,3069527,"boy band,dance pop,pop,post-teen pop",10,2006,M,Group
3,3,Drake,41420478,"canadian hip hop,canadian pop,hip hop,pop rap,...",11,2010,M,Solo
4,4,Chris Brown,9676862,"dance pop,pop,pop rap,r&b,rap",6,2005,M,Solo
...,...,...,...,...,...,...,...,...
1028,1028,Mercedes Sosa,404861,"argentine rock,cantautor,folklore argentino,nu...",64,1962,F,Solo
1030,1030,Dwight Yoakam,284597,"country,country rock,nashville sound,outlaw co...",25,1985,M,Solo
1032,1032,Lila McCann,42444,"contemporary country,country,country dawn",4,1997,F,Solo
1033,1033,Everlast,200550,rap rock,11,1990,M,Solo
1034,1034,Collective Soul,525701,"alternative metal,alternative rock,pop rock,po...",12,1994,M,Group

In [39]:
df = df.drop(columns= ["Artist", "Genres", "X"])
df

      Followers  NumAlbums  YearFirstAlbum Gender Group.Solo
0      52698756          8            2011      M       Solo
1      30711450         10            2009      M       Solo
2       3069527         10            2006      M      Group
3      41420478         11            2010      M       Solo
4       9676862          6            2005      M       Solo
...         ...        ...             ...    ...        ...
1028     404861         64            1962      F       Solo
1030     284597         25            1985      M       Solo
1032      42444          4            1997      F       Solo
1033     200550         11            1990      M       Solo
1034     525701         12            1994      M      Group

[934 rows x 5 columns]

In [40]:
df_dummies = pd.get_dummies(df)
df_dummies

,Followers,NumAlbums,YearFirstAlbum,Gender_F,Gender_M,Group.Solo_Group,Group.Solo_Solo
0,52698756,8,2011,False,True,False,True
1,30711450,10,2009,False,True,False,True
2,3069527,10,2006,False,True,True,False
3,41420478,11,2010,False,True,False,True
4,9676862,6,2005,False,True,False,True
...,...,...,...,...,...,...,...
1028,404861,64,1962,True,False,False,True
1030,284597,25,1985,False,True,False,True
1032,42444,4,1997,True,False,False,True
1033,200550,11,1990,False,True,False,True
1034,525701,12,1994,False,True,True,False

In [41]:
X = df_dummies.drop(columns = ["Followers"])
y = df_dummies["Followers"]

X = X.astype(np.float32)
y = y.astype(np.float32)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [42]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [43]:
# Define the model
model = Sequential()
model.add(Dense(64, input_dim=X.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))  # Output layer with one neuron for regression

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100

18/18 [==============================] - 1s 10ms/step - loss: 20280078499840.0000 - val_loss: 19467098652672.0000
Epoch 2/100
18/18 [==============================] - 0s 4ms/step - loss: 20280076402688.0000 - val_loss: 19467096555520.0000
Epoch 3/100
18/18 [==============================] - 0s 4ms/step - loss: 20280074305536.0000 - val_loss: 19467088166912.0000
Epoch 4/100
18/18 [==============================] - 0s 4ms/step - loss: 20280063819776.0000 - val_loss: 19467077681152.0000
Epoch 5/100
18/18 [==============================] - 0s 4ms/step - loss: 20280055431168.0000 - val_loss: 19467063001088.0000
Epoch 6/100
18/18 [==============================] - 0s 4ms/step - loss: 20280040751104.0000 - val_loss: 19467042029568.0000
Epoch 7/100
18/18 [==============================] - 0s 4ms/step - loss: 20280019779584.0000 - val_loss: 19467016863744.0000
Epoch 8/100
18/18 [==============================] - 0s 4ms/step - loss: 20279990419456.0000 - val_loss: 19466977017856.0000
Epoch 9/100
18/18 [==============================] - 0s 4ms/step - loss: 20279952670720.0000 - val_loss: 19466930880512.0000
Epoch 10/100
18/18 [==============================] - 0s 4ms/step - loss: 20279906533376.0000 - val_loss: 19466878451712.0000
Epoch 11/100
18/18 [==============================] - 0s 4ms/step - loss: 20279847813120.0000 - val_loss: 19466807148544.0000
Epoch 12/100
18/18 [==============================] - 0s 4ms/step - loss: 20279784898560.0000 - val_loss: 19466725359616.0000
Epoch 13/100
18/18 [==============================] - 0s 3ms/step - loss: 20279698915328.0000 - val_loss: 19466626793472.0000
Epoch 14/100
18/18 [==============================] - 0s 4ms/step - loss: 20279608737792.0000 - val_loss: 19466509352960.0000
Epoch 15/100
18/18 [==============================] - 0s 3ms/step - loss: 20279491297280.0000 - val_loss: 19466375135232.0000
Epoch 16/100
18/18 [==============================] - 0s 4ms/step - loss: 20279357079552.0000 - val_loss: 19466224140288.0000
Epoch 17/100
18/18 [==============================] - 0s 4ms/step - loss: 20279210278912.0000 - val_loss: 19466041688064.0000
Epoch 18/100
18/18 [==============================] - 0s 4ms/step - loss: 20279036215296.0000 - val_loss: 19465836167168.0000
Epoch 19/100
18/18 [==============================] - 0s 3ms/step - loss: 20278836985856.0000 - val_loss: 19465603383296.0000
Epoch 20/100
18/18 [==============================] - 0s 4ms/step - loss: 20278610493440.0000 - val_loss: 19465343336448.0000
Epoch 21/100
18/18 [==============================] - 0s 4ms/step - loss: 20278365126656.0000 - val_loss: 19465058123776.0000
Epoch 22/100
18/18 [==============================] - 0s 3ms/step - loss: 20278094594048.0000 - val_loss: 19464743550976.0000
Epoch 23/100
18/18 [==============================] - 0s 4ms/step - loss: 20277790507008.0000 - val_loss: 19464399618048.0000
Epoch 24/100
18/18 [==============================] - 0s 4ms/step - loss: 20277461254144.0000 - val_loss: 19464009547776.0000
Epoch 25/100
18/18 [==============================] - 0s 4ms/step - loss: 20277100544000.0000 - val_loss: 19463588020224.0000
Epoch 26/100
18/18 [==============================] - 0s 4ms/step - loss: 20276702085120.0000 - val_loss: 19463166492672.0000
Epoch 27/100
18/18 [==============================] - 0s 4ms/step - loss: 20276297334784.0000 - val_loss: 19462684147712.0000
Epoch 28/100
18/18 [==============================] - 0s 3ms/step - loss: 20275819184128.0000 - val_loss: 19462195511296.0000
Epoch 29/100
18/18 [==============================] - 0s 3ms/step - loss: 20275351519232.0000 - val_loss: 19461604114432.0000
Epoch 30/100
18/18 [==============================] - 0s 4ms/step - loss: 20274814648320.0000 - val_loss: 19461014814720.0000
Epoch 31/100
18/18 [==============================] - 0s 4ms/step - loss: 20274265194496.0000 - val_loss: 19460385669120.0000
Epoch 32/100
18/18 [==============================] - 0s 4ms/step - loss: 20273677991936.0000 - val_loss: 19459725066240.0000
Epoch 33/100
18/18 [==============================] - 0s 3ms/step - loss: 20273063526400.0000 - val_loss: 19459009937408.0000
Epoch 34/100
18/18 [==============================] - 0s 4ms/step - loss: 20272381952000.0000 - val_loss: 19458265448448.0000
Epoch 35/100
18/18 [==============================] - 0s 3ms/step - loss: 20271668920320.0000 - val_loss: 19457483210752.0000
Epoch 36/100
18/18 [==============================] - 0s 4ms/step - loss: 20270928625664.0000 - val_loss: 19456635961344.0000
Epoch 37/100
18/18 [==============================] - 0s 4ms/step - loss: 20270117027840.0000 - val_loss: 19455765643264.0000
Epoch 38/100
18/18 [==============================] - 0s 4ms/step - loss: 20269305430016.0000 - val_loss: 19454765301760.0000
Epoch 39/100
18/18 [==============================] - 0s 4ms/step - loss: 20268382683136.0000 - val_loss: 19453800611840.0000
Epoch 40/100
18/18 [==============================] - 0s 4ms/step - loss: 20267497684992.0000 - val_loss: 19452766715904.0000
Epoch 41/100
18/18 [==============================] - 0s 4ms/step - loss: 20266509926400.0000 - val_loss: 19451730722816.0000
Epoch 42/100
18/18 [==============================] - 0s 4ms/step - loss: 20265522167808.0000 - val_loss: 19450619232256.0000
Epoch 43/100
18/18 [==============================] - 0s 3ms/step - loss: 20264505049088.0000 - val_loss: 19449421758464.0000
Epoch 44/100
18/18 [==============================] - 0s 4ms/step - loss: 20263385169920.0000 - val_loss: 19448264130560.0000
Epoch 45/100
18/18 [==============================] - 0s 4ms/step - loss: 20262263193600.0000 - val_loss: 19446965993472.0000
Epoch 46/100
18/18 [==============================] - 0s 4ms/step - loss: 20261057331200.0000 - val_loss: 19445583970304.0000
Epoch 47/100
18/18 [==============================] - 0s 3ms/step - loss: 20259826302976.0000 - val_loss: 19444176781312.0000
Epoch 48/100
18/18 [==============================] - 0s 3ms/step - loss: 20258490417152.0000 - val_loss: 19442811535360.0000
Epoch 49/100
18/18 [==============================] - 0s 4ms/step - loss: 20257179697152.0000 - val_loss: 19441333043200.0000
Epoch 50/100
18/18 [==============================] - 0s 3ms/step - loss: 20255801868288.0000 - val_loss: 19439776956416.0000
Epoch 51/100
18/18 [==============================] - 0s 4ms/step - loss: 20254361124864.0000 - val_loss: 19438231355392.0000
Epoch 52/100
18/18 [==============================] - 0s 4ms/step - loss: 20252926672896.0000 - val_loss: 19436589285376.0000
Epoch 53/100
18/18 [==============================] - 0s 3ms/step - loss: 20251322351616.0000 - val_loss: 19434940923904.0000
Epoch 54/100
18/18 [==============================] - 0s 4ms/step - loss: 20249799819264.0000 - val_loss: 19433124790272.0000
Epoch 55/100
18/18 [==============================] - 0s 4ms/step - loss: 20248153554944.0000 - val_loss: 19431325433856.0000
Epoch 56/100
18/18 [==============================] - 0s 3ms/step - loss: 20246480027648.0000 - val_loss: 19429463162880.0000
Epoch 57/100
18/18 [==============================] - 0s 3ms/step - loss: 20244741488640.0000 - val_loss: 19427579920384.0000
Epoch 58/100
18/18 [==============================] - 0s 3ms/step - loss: 20242937937920.0000 - val_loss: 19425677803520.0000
Epoch 59/100
18/18 [==============================] - 0s 3ms/step - loss: 20241115512832.0000 - val_loss: 19423691800576.0000
Epoch 60/100
18/18 [==============================] - 0s 4ms/step - loss: 20239299379200.0000 - val_loss: 19421428973568.0000
Epoch 61/100
18/18 [==============================] - 0s 4ms/step - loss: 20237258850304.0000 - val_loss: 19419287781376.0000
Epoch 62/100
18/18 [==============================] - 0s 3ms/step - loss: 20235243487232.0000 - val_loss: 19417071091712.0000
Epoch 63/100
18/18 [==============================] - 0s 4ms/step - loss: 20233154723840.0000 - val_loss: 19414713892864.0000
Epoch 64/100
18/18 [==============================] - 0s 4ms/step - loss: 20230979977216.0000 - val_loss: 19412381859840.0000
Epoch 65/100
18/18 [==============================] - 0s 5ms/step - loss: 20228750704640.0000 - val_loss: 19409961746432.0000
Epoch 66/100
18/18 [==============================] - 0s 4ms/step - loss: 20226540306432.0000 - val_loss: 19407424192512.0000
Epoch 67/100
18/18 [==============================] - 0s 4ms/step - loss: 20224181010432.0000 - val_loss: 19404884541440.0000
Epoch 68/100
18/18 [==============================] - 0s 4ms/step - loss: 20221836394496.0000 - val_loss: 19402195992576.0000
Epoch 69/100
18/18 [==============================] - 0s 4ms/step - loss: 20219351269376.0000 - val_loss: 19399511638016.0000
Epoch 70/100
18/18 [==============================] - 0s 3ms/step - loss: 20216824201216.0000 - val_loss: 19396747591680.0000
Epoch 71/100
18/18 [==============================] - 0s 3ms/step - loss: 20214225829888.0000 - val_loss: 19394050654208.0000
Epoch 72/100
18/18 [==============================] - 0s 4ms/step - loss: 20211702956032.0000 - val_loss: 19390942674944.0000
Epoch 73/100
18/18 [==============================] - 0s 4ms/step - loss: 20208936812544.0000 - val_loss: 19388015050752.0000
Epoch 74/100
18/18 [==============================] - 0s 4ms/step - loss: 20206151794688.0000 - val_loss: 19385116786688.0000
Epoch 75/100
18/18 [==============================] - 0s 5ms/step - loss: 20203394039808.0000 - val_loss: 19381941698560.0000
Epoch 76/100
18/18 [==============================] - 0s 4ms/step - loss: 20200573370368.0000 - val_loss: 19378724667392.0000
Epoch 77/100
18/18 [==============================] - 0s 3ms/step - loss: 20197628968960.0000 - val_loss: 19375497150464.0000
Epoch 78/100
18/18 [==============================] - 0s 4ms/step - loss: 20194548252672.0000 - val_loss: 19372359811072.0000
Epoch 79/100
18/18 [==============================] - 0s 4ms/step - loss: 20191599656960.0000 - val_loss: 19369029533696.0000
Epoch 80/100
18/18 [==============================] - 0s 3ms/step - loss: 20188506357760.0000 - val_loss: 19365539872768.0000
Epoch 81/100
18/18 [==============================] - 0s 4ms/step - loss: 20185272549376.0000 - val_loss: 19362073280512.0000
Epoch 82/100
18/18 [==============================] - 0s 4ms/step - loss: 20182080684032.0000 - val_loss: 19358451499008.0000
Epoch 83/100
18/18 [==============================] - 0s 3ms/step - loss: 20178689589248.0000 - val_loss: 19354739539968.0000
Epoch 84/100
18/18 [==============================] - 0s 4ms/step - loss: 20175334146048.0000 - val_loss: 19351021289472.0000
Epoch 85/100
18/18 [==============================] - 0s 4ms/step - loss: 20171940954112.0000 - val_loss: 19347227541504.0000
Epoch 86/100
18/18 [==============================] - 0s 4ms/step - loss: 20168348532736.0000 - val_loss: 19343335227392.0000
Epoch 87/100
18/18 [==============================] - 0s 4ms/step - loss: 20164741431296.0000 - val_loss: 19339390484480.0000
Epoch 88/100
18/18 [==============================] - 0s 4ms/step - loss: 20161134329856.0000 - val_loss: 19335294746624.0000
Epoch 89/100
18/18 [==============================] - 0s 4ms/step - loss: 20157432856576.0000 - val_loss: 19331194814464.0000
Epoch 90/100
18/18 [==============================] - 0s 4ms/step - loss: 20153630720000.0000 - val_loss: 19327191351296.0000
Epoch 91/100
18/18 [==============================] - 0s 4ms/step - loss: 20149906178048.0000 - val_loss: 19323038990336.0000
Epoch 92/100
18/18 [==============================] - 0s 4ms/step - loss: 20146034835456.0000 - val_loss: 19318662234112.0000
Epoch 93/100
18/18 [==============================] - 0s 4ms/step - loss: 20141945389056.0000 - val_loss: 19314335809536.0000
Epoch 94/100
18/18 [==============================] - 0s 4ms/step - loss: 20137950314496.0000 - val_loss: 19309992607744.0000
Epoch 95/100
18/18 [==============================] - 0s 4ms/step - loss: 20133896519680.0000 - val_loss: 19305540354048.0000
Epoch 96/100
18/18 [==============================] - 0s 3ms/step - loss: 20129748353024.0000 - val_loss: 19301056643072.0000
Epoch 97/100
18/18 [==============================] - 0s 4ms/step - loss: 20125614866432.0000 - val_loss: 19296222707712.0000
Epoch 98/100
18/18 [==============================] - 0s 4ms/step - loss: 20121259081728.0000 - val_loss: 19291569127424.0000
Epoch 99/100
18/18 [==============================] - 0s 4ms/step - loss: 20116865548288.0000 - val_loss: 19286720512000.0000
Epoch 100/100
18/18 [==============================] - 0s 4ms/step - loss: 20112365060096.0000 - val_loss: 19282062737408.0000